export const ALL_SYMPTOMS = [
  "high_fever","mild_fever","low_grade_fever","chills","rigors",
  "night_sweats","sweating","fatigue","malaise","lethargy",
  "weakness","weight_loss","weight_gain","loss_of_appetite",
  "increased_appetite","excessive_thirst","dehydration",
  "headache","severe_headache","chest_pain","abdominal_pain",
  "stomach_pain","back_pain","neck_pain","joint_pain","muscle_pain",
  "bone_pain","knee_pain","hip_joint_pain","throat_pain",
  "pain_behind_eyes","ear_pain","pelvic_pain",
  "cough","dry_cough","productive_cough","breathlessness",
  "wheezing","chest_tightness","rapid_breathing","noisy_breathing",
  "runny_nose","nasal_congestion","sneezing","sore_throat",
  "hoarseness","blood_in_sputum","phlegm","mucoid_sputum",
  "nausea","vomiting","diarrhoea","bloody_diarrhoea","constipation",
  "bloating","indigestion","acidity","heartburn","regurgitation",
  "difficulty_swallowing","loss_of_smell","loss_of_taste",
  "stomach_bleeding","black_tarry_stool","bloody_stool",
  "mucus_in_stool","abdominal_distension","passage_of_gases",
  "jaundice","yellowish_skin","yellowing_of_eyes","dark_urine",
  "pale_stool","palpitations","fast_heart_rate","irregular_heartbeat",
  "chest_pressure","ankle_swelling","leg_swelling",
  "swollen_blood_vessels","prominent_veins_on_calf","cold_extremities",
  "dizziness","vertigo","loss_of_balance","fainting","seizures",
  "confusion","altered_consciousness","memory_loss","slurred_speech",
  "facial_drooping","limb_weakness","numbness","tingling",
  "visual_disturbances","double_vision","blurred_vision",
  "sensitivity_to_light","sensitivity_to_sound","stiff_neck",
  "neck_rigidity","burning_urination","frequent_urination",
  "painful_urination","blood_in_urine","cloudy_urine",
  "reduced_urine_output","polyuria","incontinence",
  "skin_rash","itching","hives","blisters","skin_peeling",
  "redness","swelling","nodules","pustules","dry_skin",
  "oily_skin","hair_loss","nail_changes","bruising",
  "bleeding_tendency","petechiae","red_eyes","watery_eyes",
  "eye_discharge","ear_discharge","hearing_loss","ringing_in_ears",
  "mouth_ulcers","swollen_lymph_nodes","enlarged_tonsils",
  "excessive_hunger","irregular_periods","missed_period",
  "hot_flushes","cold_intolerance","heat_intolerance",
  "tremors","enlarged_thyroid","puffiness",
  "anxiety","depression_symptoms","irritability","mood_swings",
  "sleep_disturbance","restlessness","poor_concentration",
  "muscle_cramps","muscle_stiffness","joint_stiffness",
  "reduced_mobility","difficulty_walking","falls",
]

export const SYMPTOM_LABELS = Object.fromEntries(
  ALL_SYMPTOMS.map(s => [s, s.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())])
)

export const SYMPTOM_CATEGORIES = {
  "Fever & Systemic": [
    "high_fever","mild_fever","low_grade_fever","chills","rigors",
    "night_sweats","sweating","fatigue","malaise","lethargy",
    "weakness","dehydration",
  ],
  "Pain": [
    "headache","severe_headache","chest_pain","abdominal_pain",
    "stomach_pain","back_pain","neck_pain","joint_pain","muscle_pain",
    "bone_pain","knee_pain","hip_joint_pain","throat_pain",
    "pain_behind_eyes","ear_pain","pelvic_pain",
  ],
  "Respiratory": [
    "cough","dry_cough","productive_cough","breathlessness",
    "wheezing","chest_tightness","rapid_breathing","runny_nose",
    "nasal_congestion","sneezing","sore_throat","hoarseness",
    "blood_in_sputum","phlegm",
  ],
  "Digestive": [
    "nausea","vomiting","diarrhoea","constipation","bloating",
    "indigestion","acidity","heartburn","stomach_bleeding",
    "black_tarry_stool","bloody_stool","abdominal_distension",
    "jaundice","yellowish_skin","yellowing_of_eyes","dark_urine",
  ],
  "Cardiovascular": [
    "palpitations","fast_heart_rate","irregular_heartbeat",
    "chest_pressure","ankle_swelling","leg_swelling",
    "cold_extremities","prominent_veins_on_calf",
  ],
  "Neurological": [
    "dizziness","vertigo","loss_of_balance","fainting","seizures",
    "confusion","altered_consciousness","memory_loss","slurred_speech",
    "facial_drooping","limb_weakness","numbness","tingling",
    "visual_disturbances","sensitivity_to_light","stiff_neck","neck_rigidity",
  ],
  "Urinary": [
    "burning_urination","frequent_urination","painful_urination",
    "blood_in_urine","cloudy_urine","reduced_urine_output",
    "polyuria","incontinence",
  ],
  "Skin": [
    "skin_rash","itching","hives","blisters","skin_peeling",
    "redness","swelling","nodules","pustules","dry_skin",
    "hair_loss","nail_changes","bruising","petechiae",
  ],
  "Weight & Appetite": [
    "weight_loss","weight_gain","loss_of_appetite",
    "increased_appetite","excessive_thirst","excessive_hunger",
  ],
  "Hormonal": [
    "irregular_periods","missed_period","hot_flushes",
    "cold_intolerance","heat_intolerance","tremors",
    "enlarged_thyroid","puffiness",
  ],
  "Mental Health": [
    "anxiety","depression_symptoms","irritability","mood_swings",
    "sleep_disturbance","restlessness","poor_concentration",
  ],
  "Musculoskeletal": [
    "muscle_cramps","muscle_stiffness","joint_stiffness",
    "reduced_mobility","difficulty_walking","falls",
  ],
}